DEVISE_SECRET_KEY:
DEVISE_SEND_MAIL_FROM:
AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:
NEW_RELIC_LICENSE_KEY:
NEW_RELIC_APP_NAME:
development:
  SENDGRID_USERNAME: app25225351@heroku.com
  SENDGRID_PASSWORD: bbtn3xio
  AWS_BUCKET:
production:
  AWS_BUCKET: