NEW_RELIC_LICENSE_KEY:
NEW_RELIC_APP_NAME:
SENDGRID_USERNAME:
SENDGRID_PASSWORD:
DEVISE_SECRET_KEY:
DEVISE_SEND_MAIL_FROM:
AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:
development:
  AWS_BUCKET:
production:
  AWS_BUCKET: