require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SupplementsController do

  # This should return the minimal set of attributes required to create a valid
  # Supplement. As you add validations to Supplement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SupplementsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all supplements as @supplements" do
      supplement = Supplement.create! valid_attributes
      get :index, {}, valid_session
      assigns(:supplements).should eq([supplement])
    end
  end

  describe "GET show" do
    it "assigns the requested supplement as @supplement" do
      supplement = Supplement.create! valid_attributes
      get :show, {:id => supplement.to_param}, valid_session
      assigns(:supplement).should eq(supplement)
    end
  end

  describe "GET new" do
    it "assigns a new supplement as @supplement" do
      get :new, {}, valid_session
      assigns(:supplement).should be_a_new(Supplement)
    end
  end

  describe "GET edit" do
    it "assigns the requested supplement as @supplement" do
      supplement = Supplement.create! valid_attributes
      get :edit, {:id => supplement.to_param}, valid_session
      assigns(:supplement).should eq(supplement)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Supplement" do
        expect {
          post :create, {:supplement => valid_attributes}, valid_session
        }.to change(Supplement, :count).by(1)
      end

      it "assigns a newly created supplement as @supplement" do
        post :create, {:supplement => valid_attributes}, valid_session
        assigns(:supplement).should be_a(Supplement)
        assigns(:supplement).should be_persisted
      end

      it "redirects to the created supplement" do
        post :create, {:supplement => valid_attributes}, valid_session
        response.should redirect_to(Supplement.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved supplement as @supplement" do
        # Trigger the behavior that occurs when invalid params are submitted
        Supplement.any_instance.stub(:save).and_return(false)
        post :create, {:supplement => { "name" => "invalid value" }}, valid_session
        assigns(:supplement).should be_a_new(Supplement)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Supplement.any_instance.stub(:save).and_return(false)
        post :create, {:supplement => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested supplement" do
        supplement = Supplement.create! valid_attributes
        # Assuming there are no other supplements in the database, this
        # specifies that the Supplement created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Supplement.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => supplement.to_param, :supplement => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested supplement as @supplement" do
        supplement = Supplement.create! valid_attributes
        put :update, {:id => supplement.to_param, :supplement => valid_attributes}, valid_session
        assigns(:supplement).should eq(supplement)
      end

      it "redirects to the supplement" do
        supplement = Supplement.create! valid_attributes
        put :update, {:id => supplement.to_param, :supplement => valid_attributes}, valid_session
        response.should redirect_to(supplement)
      end
    end

    describe "with invalid params" do
      it "assigns the supplement as @supplement" do
        supplement = Supplement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Supplement.any_instance.stub(:save).and_return(false)
        put :update, {:id => supplement.to_param, :supplement => { "name" => "invalid value" }}, valid_session
        assigns(:supplement).should eq(supplement)
      end

      it "re-renders the 'edit' template" do
        supplement = Supplement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Supplement.any_instance.stub(:save).and_return(false)
        put :update, {:id => supplement.to_param, :supplement => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested supplement" do
      supplement = Supplement.create! valid_attributes
      expect {
        delete :destroy, {:id => supplement.to_param}, valid_session
      }.to change(Supplement, :count).by(-1)
    end

    it "redirects to the supplements list" do
      supplement = Supplement.create! valid_attributes
      delete :destroy, {:id => supplement.to_param}, valid_session
      response.should redirect_to(supplements_url)
    end
  end

end
